/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2024-03-15 07:39:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.ssafy.fit.model.dto.Review;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(1);
    _jspx_imports_classes.add("com.ssafy.fit.model.dto.Review");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link\r\n");
      out.write("    href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("    rel=\"stylesheet\"\r\n");
      out.write("    integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\"\r\n");
      out.write("    crossorigin=\"anonymous\">\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/css/main.css\" rel=\"stylesheet\">\r\n");
      out.write("<title>ssafit</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<i class=\"ssafy\" role=\"mainIcon\"><a href=\"index.jsp\"> <svg\r\n");
      out.write("						xmlns=\"http://www.w3.org/2000/svg\" fill=\"currentColor\"\r\n");
      out.write("						class=\"bi bi-amd\" viewBox=\"0 0 16 16\">\r\n");
      out.write("          <path\r\n");
      out.write("							d=\"m.334 0 4.358 4.359h7.15v7.15l4.358 4.358V0zM.2 9.72l4.487-4.488v6.281h6.28L6.48 16H.2z\" />\r\n");
      out.write("        </svg>\r\n");
      out.write("			</a> </i>\r\n");
      out.write("			<div class=\"menu\">\r\n");
      out.write("				<a href=\"index.jsp\" class=\"home\"><span>home</span></a> <a\r\n");
      out.write("					href=\"index.jsp\" class=\"searchGym\"><span>헬스장 찾기</span></a> <i\r\n");
      out.write("					class=\"signUp\"><a href=\"#\"> <svg\r\n");
      out.write("							xmlns=\"http://www.w3.org/2000/svg\" fill=\"currentColor\"\r\n");
      out.write("							class=\"bi bi-person-fill-add\" viewBox=\"0 0 16 16\">\r\n");
      out.write("            <path\r\n");
      out.write("								d=\"M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7m.5-5v1h1a.5.5 0 0 1 0 1h-1v1a.5.5 0 0 1-1 0v-1h-1a.5.5 0 0 1 0-1h1v-1a.5.5 0 0 1 1 0m-2-6a3 3 0 1 1-6 0 3 3 0 0 1 6 0\" />\r\n");
      out.write("            <path\r\n");
      out.write("								d=\"M2 13c0 1 1 1 1 1h5.256A4.5 4.5 0 0 1 8 12.5a4.5 4.5 0 0 1 1.544-3.393Q8.844 9.002 8 9c-5 0-6 3-6 4\" />\r\n");
      out.write("          </svg>\r\n");
      out.write("				</a> </i> <i class=\"login\"><a href=\"#\"> <svg\r\n");
      out.write("							xmlns=\"http://www.w3.org/2000/svg\" fill=\"currentColor\"\r\n");
      out.write("							class=\"bi bi-box-arrow-in-right\" viewBox=\"0 0 16 16\">\r\n");
      out.write("            <path fill-rule=\"evenodd\"\r\n");
      out.write("								d=\"M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0z\" />\r\n");
      out.write("            <path fill-rule=\"evenodd\"\r\n");
      out.write("								d=\"M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z\" />\r\n");
      out.write("          </svg>\r\n");
      out.write("				</a> </i>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"picture\">\r\n");
      out.write("		<div id=\"carouselExampleControls\" class=\"carousel slide\"\r\n");
      out.write("			data-bs-ride=\"carousel\">\r\n");
      out.write("			<div class=\"carousel-inner\">\r\n");
      out.write("				<div class=\"carousel-item active\">\r\n");
      out.write("					<img\r\n");
      out.write("						src=\"https://www.noblesse.com/shop/data/m/editor_new/2021/09/09/b0342c6ba3cff4bf1.jpg\"\r\n");
      out.write("						class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"carousel-item\">\r\n");
      out.write("					<img src=\"/PJT_0315/src/main/resources/img/11.png\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"carousel-item\">\r\n");
      out.write("					<img src=\"/PJT_0315/src/main/resources/img/22.png\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<button class=\"carousel-control-prev\" type=\"button\"\r\n");
      out.write("				data-bs-target=\"#carouselExampleControls\" data-bs-slide=\"prev\">\r\n");
      out.write("				<span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("				<span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("			</button>\r\n");
      out.write("			<button class=\"carousel-control-next\" type=\"button\"\r\n");
      out.write("				data-bs-target=\"#carouselExampleControls\" data-bs-slide=\"next\">\r\n");
      out.write("				<span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("				<span class=\"visually-hidden\">Next</span>\r\n");
      out.write("			</button>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<main>\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"searchDiv\">\r\n");
      out.write("				<div class=\"_Box\">\r\n");
      out.write("					<i class=\"searchIcon\"> <svg xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("							fill=\"currentColor\" class=\"bi bi-search\" viewBox=\"0 0 16 16\">\r\n");
      out.write("            <path\r\n");
      out.write("								d=\"M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0\" />\r\n");
      out.write("          </svg>\r\n");
      out.write("					</i>\r\n");
      out.write("					<form method=\"get\">\r\n");
      out.write("						<input type=\"text\" placeholder=\"운동 제목 검색\">\r\n");
      out.write("\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"mostSee\">\r\n");
      out.write("				<h1>최근 가장 많이 본 영상</h1>\r\n");
      out.write("				<div class=\"_video\">\r\n");
      out.write("					<div id=\"dataDisplay\" class=\"goLeft arrow goLeftArrow\">&lt;</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<div id=\"goRightArrow\" class=\"goRight arrow\">&gt;</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"selectActive\">\r\n");
      out.write("				<h1>운동 부위 선택</h1>\r\n");
      out.write("				<nav class=\"_click\">\r\n");
      out.write("					<button class=\"_button body\">전신</button>\r\n");
      out.write("					<button class=\"_button top\">상체</button>\r\n");
      out.write("					<button class=\"_button down\">하체</button>\r\n");
      out.write("					<button class=\"_button middle\">복부</button>\r\n");
      out.write("				</nav>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"body body_video _video\">\r\n");
      out.write("					<div class=\"goLeft arrow getVideo\">&lt;</div>\r\n");
      out.write("					<div id=\"dontBug1\">\r\n");
      out.write("						<div class=\"nooo\">\r\n");
      out.write("							<iframe src=\"https://www.youtube.com/embed/swRNeYw1JkY\"\r\n");
      out.write("								allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\"\r\n");
      out.write("								allowfullscreen=\"\"></iframe>\r\n");
      out.write("							<div class=\"_name\">\r\n");
      out.write("								<a href=\"review.jsp\">하루 15분! 전신 칼로리 불태우는 다이어트...</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"where\">\r\n");
      out.write("								<span>전신</span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div id=\"dontBug2\">\r\n");
      out.write("						<div class=\"nooo\">\r\n");
      out.write("							<iframe src=\"https://www.youtube.com/embed/gMaB-fG4u4g\"\r\n");
      out.write("								allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\"\r\n");
      out.write("								allowfullscreen=\"\"></iframe>\r\n");
      out.write("							<div class=\"_name\">\r\n");
      out.write("								<a href=\"review.jsp\">전신 다이어트 최고의 운동 [칼소폭 찐 핵핵...</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"where\">\r\n");
      out.write("								<span>전신</span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"goRight arrow\">&gt;</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</main>\r\n");
      out.write("\r\n");
      out.write("	<footer>\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<ul class=\"aboutSite\">\r\n");
      out.write("				<li><a href=\"\">개인정보처리방침</a></li>\r\n");
      out.write("				<li><a href=\"\">이용약관</a></li>\r\n");
      out.write("				<li><a href=\"\">오시는길</a></li>\r\n");
      out.write("				<li>&copy; SSAFY Corp.</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("	<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/buttonVideo.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/clickArrow.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/getVideo.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("		integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
